In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:/Users/nawin/wine_dataset.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
## no of classes in data
len(df['quality'].unique())

6

In [4]:
df['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

In [5]:
df['quality'].value_counts()

## the dataset is imbalanced as class 5 , 6 has larger values than class 3, 8 , 4

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [6]:
print("Basic Statistics of data:\n",df.describe().T)

Basic Statistics of data:
                        count       mean        std      min      25%  \
fixed acidity         1599.0   8.319637   1.741096  4.60000   7.1000   
volatile acidity      1599.0   0.527821   0.179060  0.12000   0.3900   
citric acid           1599.0   0.270976   0.194801  0.00000   0.0900   
residual sugar        1599.0   2.538806   1.409928  0.90000   1.9000   
chlorides             1599.0   0.087467   0.047065  0.01200   0.0700   
free sulfur dioxide   1599.0  15.874922  10.460157  1.00000   7.0000   
total sulfur dioxide  1599.0  46.467792  32.895324  6.00000  22.0000   
density               1599.0   0.996747   0.001887  0.99007   0.9956   
pH                    1599.0   3.311113   0.154386  2.74000   3.2100   
sulphates             1599.0   0.658149   0.169507  0.33000   0.5500   
alcohol               1599.0  10.422983   1.065668  8.40000   9.5000   
quality               1599.0   5.636023   0.807569  3.00000   5.0000   

                           50%      

In [7]:
df.duplicated().sum()

240

In [8]:
df=df.drop_duplicates()

In [9]:
df.duplicated().sum()

0

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X=df.drop(['quality'],axis=1)
y=df['quality']

In [12]:
## Splitting data 
X_train,X_test, y_train,y_test= train_test_split(X,y,test_size=0.30,random_state=42)

In [ ]:
## There is no need of scaling data in decision tree

In [13]:
## Create decesion tree classifier
from sklearn.tree import DecisionTreeClassifier

In [14]:
model=DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [15]:
model.predict(X_test)

array([5, 6, 7, 5, 4, 7, 4, 5, 7, 6, 6, 6, 7, 6, 6, 5, 6, 5, 5, 6, 5, 6,
       5, 4, 5, 5, 6, 5, 5, 6, 6, 6, 6, 4, 5, 6, 6, 6, 5, 7, 4, 6, 6, 5,
       5, 6, 5, 5, 5, 6, 6, 8, 6, 5, 7, 5, 6, 6, 5, 5, 5, 8, 6, 6, 5, 6,
       5, 5, 7, 7, 5, 8, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 5, 5, 5, 6, 5,
       6, 6, 6, 3, 5, 5, 6, 6, 4, 7, 6, 6, 6, 5, 6, 5, 8, 5, 5, 6, 5, 7,
       6, 6, 5, 5, 5, 6, 3, 5, 5, 6, 5, 5, 4, 5, 5, 5, 6, 5, 5, 5, 6, 5,
       6, 7, 5, 5, 7, 6, 6, 6, 6, 5, 7, 6, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5,
       5, 7, 5, 5, 7, 7, 5, 3, 5, 6, 5, 7, 6, 5, 6, 7, 6, 6, 7, 6, 7, 7,
       5, 5, 5, 6, 5, 6, 6, 8, 6, 6, 5, 5, 4, 6, 5, 5, 6, 5, 6, 6, 6, 5,
       6, 7, 5, 5, 5, 6, 5, 8, 5, 6, 6, 6, 6, 6, 5, 5, 7, 6, 6, 7, 5, 6,
       5, 7, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 7, 6, 6, 6, 7, 4, 5,
       6, 6, 7, 5, 5, 6, 6, 7, 6, 6, 7, 6, 6, 7, 5, 6, 6, 6, 7, 5, 5, 5,
       5, 6, 7, 6, 5, 6, 6, 5, 7, 6, 5, 5, 5, 6, 5, 6, 5, 4, 7, 7, 6, 5,
       5, 5, 7, 7, 5, 6, 6, 5, 7, 5, 5, 7, 6, 5, 5,

In [16]:
y_predict=model.predict(X_test)

In [17]:
model.score(X_train,y_train)

## value of 1 means overfitted model

1.0

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test,y_predict)

## Accuracy score less than 50 percent, so it is dump model 

0.5073529411764706

In [ ]:
## Check accuracy with Logistic , SVM ,Random Forest, XGBOOST,  Gradient Boosting , 

In [ ]:
## Logistic

In [29]:
grid_param={
    'criterion':['gini','entropy'],
    'max_depth':range(2,32,1),
    'min_samples_leaf':range(1,10,1),
    'min_samples_split':range(2,10,1),
    'splitter':['best','random']
}

In [26]:
from sklearn.model_selection import GridSearchCV

In [30]:
grid_search =GridSearchCV(estimator=model,param_grid=grid_param,cv=5)

In [31]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': range(2, 32),
                         'min_samples_leaf': range(1, 10),
                         'min_samples_split': range(2, 10),
                         'splitter': ['best', 'random']})

In [32]:
## best parameter values selected 
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 4,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'splitter': 'random'}

In [35]:
model_with_best_param =DecisionTreeClassifier(criterion='entropy',max_depth=4,min_samples_leaf=2,min_samples_split=2,splitter='random')

In [37]:
model_with_best_param.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4, min_samples_leaf=2,
                       splitter='random')

In [38]:
y_prediction2=model_with_best_param.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score

In [47]:
y_prediction2=model_with_best_params.predict(X_test)

NameError: name 'model_with_best_params' is not defined

In [46]:
accuracy_score(y_test,y_prediction2)

TypeError: 'tuple' object is not callable

In [45]:
accuracy_score=(y_test,y_prediction2)
accuracy_score

(55      5
 1291    6
 1544    7
 593     5
 1261    4
        ..
 1305    5
 1120    8
 456     5
 1076    6
 838     7
 Name: quality, Length: 408, dtype: int64,
 array([5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6,
        5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 6, 5, 5,
        6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6, 6,
        5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5,
        6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6,
        6, 6, 5, 6, 5, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6,
        6, 6, 5, 6, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5, 5,
        5, 6, 5, 5, 6, 6, 5, 6, 6, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6,
        6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 5, 5, 5, 6, 5, 6, 5, 6, 6,
        6, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 5, 5,
        5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6,
        6, 6, 6, 5, 6,